UoaWDCC/volunteers

web/src/App.tsx
web/src/pages/NotFound.tsx

- Route to main page already set up by John. 
- Set up an additional default route for when an invalid address is entered to direct user to a page not found page which allows to user to navigate back to the main page

VOL-12/set-up-page-router

---

api/index.ts
api/package-lock.json
api/routes/hello.ts
api/yarn.lock

VOL-13/backend-api-insert-delete

---

web/src/components/WelcomeStats.tsx
web/src/styles/componentStyles/WelcomeStats.css

Created new welcome message/stats component for dashboard page + css file for this component
Currently, the component scales proportionally to the view window, but I think this might have to change in the future. 
The HTML uses objects as inputs for data, this may also change in the future. The declarations of these objects are in lines 6-15.

Created new welcome message/stats component for dashboard page + css file for this component

---

web/package-lock.json
web/package.json
web/src/components/UpcomingEvent.tsx
web/src/components/UpcomingEvents.tsx
web/src/pages/MainMenu.tsx
web/src/styles/componentStyles/UpcomingEvent.css
web/src/styles/componentStyles/UpcomingEvents.css
web/yarn.lock

VOL-27/upcoming-events-tab

---

web/src/pages/MainMenu.tsx

I just deleted my component and its import from returning in MainMenu.tsx as it had a merge error the first time. hoping this solves that issue

VOL-27/upcoming-events-tab (V2)

---

api/env
web/src/components/MainPageButtonHeadings.tsx
web/src/styles/componentStyles/MainPageButtonHeadings.css

Created Main Page Button Headings

---

web/package.json
web/src/components/MainPageButtonHeadings.tsx
web/src/components/Sponsors.tsx
web/src/data/SponsorList.json
web/src/pages/MainMenu.tsx
web/yarn.lock

Description:
Fixes bugs and crashing issues.
- added interface for default button click for button headings to avoid crashing errors
-added Json back for sponsor section
- modified sponsors section code, for future modification where we grab things from DB, and perhaps have more sponsors.
- updated react-icons
Risks:
- can't think of any

Vol special/fix imports and btn

---

web/services/firebase.tsx
web/src/components/Header.tsx

- Sign in button in the <Header /> element of the homepage now causes a popup to appear for Google Sign In
- You can view the users (logged in with a Google account) from the Firebase console
Risks:
- Firebase config is exposed on the client side since dotenv does not work on the front-end
- This is apparently okay

User Authentication with Google SignIn popup

---

web/src/styles/componentStyles/MainGallery.css

temporary fix before new design for scaling issues with gallery component

fixing scaling issues with gallery component

---

web/src/components/MainGallery.tsx
web/src/data/MainGalleryEvents.json

i forgot to do this part, so editing the event names and removed auto-scroll because the scroll timer doesn't reset when pressing forward or backwards.

editing event tiltes and description, removing autoscroll

---

web/src/components/Event.tsx
web/src/components/EventsScrollContainer.tsx

Uses tailwind styles, with updated image paths
Hardcoded data
Looks like this:

All events Event component and EventsSCrollContainer component

---

web/src/firebase/StaffAuth.ts

comment out code

---

api/controllers/userController.ts
api/routes/api/users.ts

- endpoint for updating user info added

added endpoint and corresponding route for updating user info

---

web/src/components/MainGallery.tsx

adding auto scroller to gallery

adding auto scroller to gallery

---

web/src/components/Header.tsx
web/src/components/LoginModal.tsx
web/src/context/AuthenticationContext.tsx
web/src/context/AuthenticationContextProvider.tsx

- Updating LoginModal to use AuthContex
- Automatically signing out google user if they go to register form, then return to website without finishing register (when they arent in the db)

Updating LoginModal to use AuthContex

---

web/src/components/Header.tsx
web/src/components/LoginModal.tsx

adding style to website header, fixing modal exit button position

adding style to website header, fixing modal exit button position

---

api/controllers/homepage/galleryController.ts
api/controllers/homepageController.ts
api/routes/api/homepage.ts
api/routes/endpoints.ts
web/src/components/EventHighlights.tsx
web/src/components/MainGallery.tsx
web/src/components/OurAchievements.tsx
web/src/components/OurCommunity.tsx
web/src/components/Sponsors.tsx
web/src/pages/MainMenu.tsx

The home page (and all its images) is now connected to the database. The contents of the database can then be changed using fireCMS.
closes #180

Vol 180/homepage cms

---

web/src/App.tsx
web/src/components/RegisterErrorModal.tsx
web/src/components/Signup.tsx
web/src/context/RegisterModalErrorContext.tsx
web/src/context/RegisterModalErrorContextProvider.tsx

Fixed gender button to be less inclusive and added email, phone, emptyfields verification.
phone numbers can just be anything that's either 9, 10 or 11 digits.
whitespace is automatically removed for phone numbers
resolves #186

VOL-186 fix register buttons and added verification

---

web/src/App.tsx

Removed admin routes from page router. Pages and components still exist just no longer in use

Remove /admin functionality for Events

---

api/controllers/announcementController.ts
api/controllers/eventController.ts
api/controllers/userController.ts

documentation

---

web/src/components/CommunityGallery.tsx
web/src/components/CommunityGalleryCard.tsx

hopeful;;ly tjhos tfoxed tje weir d sacling tjng

Fix community scaling

---

web/package.json
web/src/components/DashboardCommunity.tsx
web/src/components/DashboardDashboard.tsx
web/src/components/Leaderboard.tsx
web/src/components/LeaderboardEntry.tsx
web/tailwind.config.js
web/yarn.lock

Created dashboard leaderboard component in frontend

Vol 204/dashboard leaderboard component

---

web/src/components/DashboardDiscover.tsx

monthly event

---

web/index.html
web/src/App.tsx

Changed the website name and icon to match the volunteering club

Vol 89/change website name and favicon

---

web/src/components/DashboardDashboard.tsx
web/src/components/Leaderboard.tsx
web/src/components/LeaderboardEntry.tsx
web/src/components/UpcomingEvent.tsx
web/src/components/WelcomeStats.tsx

fixed up dashboard

---

web/src/components/DashboardProfile.tsx
web/src/components/ProfileMyProfileHeading.tsx
web/src/components/ProfileMyProfileOverview.tsx
web/src/components/ProfileMyProfileProgressBar.tsx

- some dimensions of the dashboard template do not fit figma design at the moment so may look awkward (will probably fix itself when sidebar is done)
- details are hardcoded => need to link to data base

plug in profile components (details hardcoded)

---

web/src/components/Dashboard/DashboardDiscover/DashboardDiscover.tsx
web/src/components/Dashboard/DashboardDiscover/Event.tsx
web/src/components/Dashboard/DashboardDiscover/EventDetails.tsx
web/src/components/Dashboard/DashboardDiscover/EventsScrollContainer.tsx
web/src/components/DashboardHeader.tsx
web/src/components/Leaderboard.tsx
web/src/components/SideBar.tsx

Create the event detail page when clicking on an event in the discover tab
closes #225

225 dashboard event details page

---

.gitignore
api/package-lock.json
api/package.json
api/yarn.lock
web/src/components/main/Footer.tsx

Added Facebook and Instagram links on main menu footer

239 home page link the social media links on home page to actual uoa voluntters links

---

web/src/pages/Dashboard.tsx

closes https://github.com/UoaWDCC/volunteers/issues/251

added calendar back to the dashboard

---

web/src/components/Dashboard/DashboardDiscover/DashboardDiscover.tsx

- Fixed image stretching
- Removed white space by centering image (removed an extra div that was hopefully useless?)

Fixed image stretching and extra white space at the bottom

---

api/yarn.lock
web/src/components/TestComponent.tsx

- Updated api yarn lock
- Resolved import error in TestComponent.tsx

Fix deployment

---

api/controllers/userController.ts
api/routes/api/users.ts
web/src/App.tsx
web/src/components/Dashboard/dashboardProfile/DashboardProfile.tsx
web/src/components/Dashboard/dashboardProfile/ProfileMyProfileOverview.tsx
web/src/context/AuthenticationContextProvider.tsx
web/yarn.lock

#231 
- MyProfile page now uses user details using authcontext.

filesforjostosee

---

web/src/components/Dashboard/dashboardDashboard/WelcomeStats.tsx
web/src/components/register/Signup.tsx

Created the levelling system and connected the welcome stats in the dashboard to the backend
closes #272

Vol 272/levelling system

---

api/config/firebase.tsx
package.json
web/Dockerfile.staging
web/src/components/Dashboard/DashboardCommunity/CommunityGallery.tsx
web/src/components/Dashboard/DashboardCommunity/CommunityGalleryWhole.tsx
web/src/components/Dashboard/DashboardDiscover/DashboardDiscover.tsx
web/src/components/main/EventHighlights.tsx
web/src/components/main/MainGallery.tsx
web/src/components/main/OurAchievements.tsx
web/src/components/main/OurCommunity.tsx
web/src/components/main/SponsorsList.tsx
web/src/context/AuthenticationContextProvider.tsx
web/src/utils/UserService.ts
yarn.lock

Changed ENV VITE_APP_URL
changed the way credentials works

Docker deploy

---

web/src/components/Dashboard/DashboardDiscover/EventDetails.tsx

Added function to the button on the event details page to sign up and unregister. Also added confirmation popup when unregistering.

Register/Unregister Function to Button

---

web/src/components/main/Header.tsx
web/src/context/AuthenticationContextProvider.tsx

When user is not found in the db, isUserLoggedIn and currentUser set to false and null; therefore main page will be showing sign-in button instead of my-page when user stops while signing up.

Changed user status when user is not found in the db

---

web/src/components/Dashboard/DashboardHeader.tsx
web/src/context/AuthenticationContext.tsx
web/src/context/AuthenticationContextProvider.tsx

Fixed Hardcoded Display Name in DashboardHeader
Issue: The display name in DashboardHeader.tsx was hardcoded as "John Doe", making it static and unchangeable.
Changes Made:
Updated AuthenticationContextProvider.tsx:
Added a new inline type named AuthContext to define variable types for authentication information.
Applied the typed context to contextValue, allowing the removal of the as any type assertion.
Modified AuthenticationContext.tsx:
The context is now properly typed using the AuthContext interface instead of being set to null.
Fixed DashboardHeader.tsx:
Replaced the hardcoded "John Doe" with the dynamically fetched displayName from the authentication context.
Files Edited:
AuthenticationContext.tsx
AuthenticationContextProvider.tsx
DashboardHeader.tsx
This ensures the display name …

Fixed #319

---

web/src/components/Dashboard/dashboardProfile/ProfileEditModal.tsx

- Change in colour in ProfileEditModal.
- Changed the bootstrap configuration's colour.

Changed delete button colour
